#!/usr/bin/env node
// Generate THIRD_PARTY_NOTICES.md from production npm dependencies + bundled fonts.
// Run via: npm run notices
import { init } from 'license-checker-rseidelsohn'
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const OUT = join(ROOT, 'THIRD_PARTY_NOTICES.md')

const packages = await new Promise((resolve, reject) => {
  init(
    { start: ROOT, production: true, excludePrivatePackages: true },
    (err, pkgs) => (err ? reject(err) : resolve(pkgs)),
  )
})

const rows = []
for (const [id, info] of Object.entries(packages)) {
  if (id.startsWith('lodestar@')) continue
  const name = id.replace(/@[^@]+$/, '')
  rows.push({
    id,
    name,
    license: info.licenses ?? 'UNKNOWN',
    repo: info.repository ?? '',
    publisher: info.publisher ?? '',
    licenseText: info.licenseFile
      ? await readFile(info.licenseFile, 'utf8').catch(() => '')
      : '',
  })
}

rows.sort((a, b) => a.name.localeCompare(b.name))

const fontSection = `
## Bundled fonts

### Geist & Geist Mono — SIL Open Font License 1.1
© 2024 The Geist Project Authors (https://github.com/vercel/geist-font)
Full text in \`src/assets/fonts/geist/OFL.txt\`.

### Instrument Serif — SIL Open Font License 1.1
© 2020 Instrument (https://github.com/Instrument/instrument-serif)
Full text in \`src/assets/fonts/instrument-serif/OFL.txt\`.
`

const header = `# Third-Party Notices

Lodestar bundles the following third-party components. Each retains its
original license. This file is auto-generated by \`npm run notices\` — do
not edit by hand.

_Generated ${new Date().toISOString().slice(0, 10)} from ${rows.length} production dependencies._
${fontSection}
---

## npm dependencies
`

const body = rows
  .map((r) => {
    const lines = []
    lines.push(`### ${r.id}`)
    lines.push(`- License: ${r.license}`)
    if (r.repo) lines.push(`- Repository: ${r.repo}`)
    if (r.publisher) lines.push(`- Publisher: ${r.publisher}`)
    if (r.licenseText) {
      lines.push('')
      lines.push('<details><summary>License text</summary>')
      lines.push('')
      lines.push('```')
      lines.push(r.licenseText.trim())
      lines.push('```')
      lines.push('')
      lines.push('</details>')
    }
    return lines.join('\n')
  })
  .join('\n\n')

await writeFile(OUT, header + '\n' + body + '\n')
console.log(`Wrote ${OUT} (${rows.length} packages)`)
